export const surahs = [
    { number: 1, name: "Al-Fatiha", englishName: "The Opener" },
    { number: 2, name: "Al-Baqarah", englishName: "The Cow" },
    { number: 3, name: "Al-Imran", englishName: "Family of Imran" },
    { number: 4, name: "An-Nisa", englishName: "The Women" },
    { number: 5, name: "Al-Ma'idah", englishName: "The Table Spread" },
    { number: 6, name: "Al-Anam", englishName: "The Cattle" },
    { number: 7, name: "Al-A'raf", englishName: "The Heights" },
    { number: 8, name: "Al-Anfal", englishName: "The Spoils of War" },
    { number: 9, name: "At-Taubah", englishName: "The Repentance" },
    { number: 10, name: "Yunus", englishName: "Jonah" },
    { number: 11, name: "Hud", englishName: "Hud" },
    { number: 12, name: "Yusuf", englishName: "Joseph" },
    { number: 13, name: "Ar-Ra'd", englishName: "Thunder" },
    { number: 14, name: "Ibrahim", englishName: "Abraham" },
    { number: 15, name: "Al-Hijr", englishName: "The Stoneland" },
    { number: 16, name: "An-Nahl", englishName: "The Bee" },
    { number: 17, name: "Al-Isra", englishName: "The Night Journey" },
    { number: 18, name: "Al-Kahf", englishName: "The Cave" },
    { number: 19, name: "Maryam", englishName: "Mary" },
    { number: 20, name: "Ta-Ha", englishName: "Ta-Ha" },
    { number: 21, name: "Al-Anbiya", englishName: "The Prophets" },
    { number: 22, name: "Al-Hajj", englishName: "The Pilgrimage" },
    { number: 23, name: "Al-Mu'minun", englishName: "The Believers" },
    { number: 24, name: "An-Nur", englishName: "The Light" },
    { number: 25, name: "Al-Furqan", englishName: "The Criterion" },
    { number: 26, name: "Ash-Shu'ara", englishName: "The Poets" },
    { number: 27, name: "An-Naml", englishName: "The Ants" },
    { number: 28, name: "Al-Qasas", englishName: "The Story" },
    { number: 29, name: "Al-Ankabut", englishName: "The Spider" },
    { number: 30, name: "Ar-Rum", englishName: "The Romans" },
    { number: 31, name: "Luqman", englishName: "Luqman" },
    { number: 32, name: "As-Sajdah", englishName: "Prostration" },
    { number: 33, name: "Al-Ahzab", englishName: "The Confederates" },
    { number: 34, name: "Saba", englishName: "Sheba" },
    { number: 35, name: "Fatir", englishName: "The Originator" },
    { number: 36, name: "Ya-Sin", englishName: "Ya Sin" },
    { number: 37, name: "As-Saffat", englishName: "Those Who Set the Ranks" },
    { number: 38, name: "Sad", englishName: "The letter Saad" },
    { number: 39, name: "Az-Zumar", englishName: "The Troops" },
    { number: 40, name: "Ghafir", englishName: "The Forgiver" },
    { number: 41, name: "Fussilat", englishName: "Explained in Detail" },
    { number: 42, name: "Ash-Shura", englishName: "The Consultation" },
    { number: 43, name: "Az-Zukhruf", englishName: "The Ornaments of Gold" },
    { number: 44, name: "Ad-Dukhan", englishName: "The Smoke" },
    { number: 45, name: "Al-Jathiyah", englishName: "The Crouching" },
    { number: 46, name: "Al-Ahqaf", englishName: "The Wind Curved Sandhill" },
    { number: 47, name: "Muhammad", englishName: "Muhammad" },
    { number: 48, name: "Al-Fath", englishName: "The Victory" },
    { number: 49, name: "Al-Hujurat", englishName: "The Private Chambers" },
    { number: 50, name: "Qaf", englishName: "Qaf" },
    { number: 51, name: "Adh-Dhariyat", englishName: "The Scatterers" },
    { number: 52, name: "At-Tur", englishName: "The Mountain" },
    { number: 53, name: "An-Najm", englishName: "The Star" },
    { number: 54, name: "Al-Qamar", englishName: "The Moon" },
    { number: 55, name: "Ar-Rahman", englishName: "The Beneficent" },
    { number: 56, name: "Al-Waqi'ah", englishName: "The Inevitable" },
    { number: 57, name: "Al-Hadid", englishName: "The Iron" },
    { number: 58, name: "Al-Mujadila", englishName: "The Pleading Women" },
    { number: 59, name: "Al-Hashr", englishName: "The Exile" },
    { number: 60, name: "Al-Mumtahanah", englishName: "She That is to be Examined" },
    { number: 61, name: "As-Saff", englishName: "The Ranks" },
    { number: 62, name: "Al-Jumu'ah", englishName: "Congregation Prayer" },
    { number: 63, name: "Al-Munafiqun", englishName: "The Hypocrites" },
    { number: 64, name: "At-Taghabun", englishName: "Mutual Dispossession" },
    { number: 65, name: "At-Talaq", englishName: "The Divorce" },
    { number: 66, name: "At-Tahrim", englishName: "The Prohibition" },
    { number: 67, name: "Al-Mulk", englishName: "The Sovereignty" },
    { number: 68, name: "Al-Qalam", englishName: "The Pen" },
    { number: 69, name: "Al-Haqqah", englishName: "The Reality" },
    { number: 70, name: "Al-Ma'arij", englishName: "The Ascending Stairways" },
    { number: 71, name: "Nuh", englishName: "Noah" },
    { number: 72, name: "Al-Jinn", englishName: "The Jinn" },
    { number: 73, name: "Al-Muzzammil", englishName: "The Enshrouded One" },
    { number: 74, name: "Al-Muddaththir", englishName: "The Cloaked One" },
    { number: 75, name: "Al-Qiyamah", englishName: "The Resurrection" },
    { number: 76, name: "Al-Insan", englishName: "The Man" },
    { number: 77, name: "Al-Mursalat", englishName: "The Emissaries" },
    { number: 78, name: "An-Naba", englishName: "The Tidings" },
    { number: 79, name: "An-Nazi'at", englishName: "Those who drag forth" },
    { number: 80, name: "Abasa", englishName: "He Frowned" },
    { number: 81, name: "At-Takwir", englishName: "The Overthrowing" },
    { number: 82, name: "Al-Infitar", englishName: "The Cleaving" },
    { number: 83, name: "Al-Mutaffifin", englishName: "The Defrauding" },
    { number: 84, name: "Al-Inshiqaq", englishName: "The Sundering" },
    { number: 84, name: "Al-Inshiqaq", englishName: "The Sundering" },
    { number: 85, name: "Al-Buruj", englishName: "The Mansions of the Stars" },
    { number: 86, name: "At-Tariq", englishName: "The Nightcomer" },
    { number: 87, name: "Al-Ala", englishName: "The Most High" },
    { number: 88, name: "Al-Ghashiyah", englishName: "The Overwhelming" },
    { number: 89, name: "Al-Fajr", englishName: "The Dawn" },
    { number: 90, name: "Al-Balad", englishName: "The City" },
    { number: 91, name: "Ash-Shams", englishName: "The Sun" },
    { number: 92, name: "Al-Lail", englishName: "The Night" },
    { number: 93, name: "Ad-Duha", englishName: "The Morning Brightness" },
    { number: 94, name: "Ash-Sharh", englishName: "The Expansion" },
    { number: 95, name: "At-Tin", englishName: "The Fig" },
    { number: 96, name: "Al-Alaq", englishName: "The Blood Clot" },
    { number: 97, name: "Al-Qadr", englishName: "The Power" },
    { number: 98, name: "Al-Bayyina", englishName: "The Evidence" },
    { number: 99, name: "Az-Zalzalah", englishName: "The Earthquake" },
    { number: 100, name: "Al-Adiyat", englishName: "The Courser" },
    { number: 101, name: "Al-Qari'ah", englishName: "The Calamity" },
    { number: 102, name: "At-Takathur", englishName: "Vying for Increase" },
    { number: 103, name: "Al-Asr", englishName: "The Declining Day" },
    { number: 104, name: "Al-Humazah", englishName: "The Slanderer" },
    { number: 105, name: "Al-Fil", englishName: "The Elephant" },
    { number: 106, name: "Quraysh", englishName: "Quraish" },
    { number: 107, name: "Al-Ma'un", englishName: "The Small Kindness" },
    { number: 108, name: "Al-Kawthar", englishName: "The Abundance" },
    { number: 109, name: "Al-Kafirun", englishName: "The Disbelievers" },
    { number: 110, name: "An-Nasr", englishName: "The Divine Support" },
    { number: 111, name: "Al-Masad", englishName: "The Palm Fiber" },
    { number: 112, name: "Al-Ikhlas", englishName: "The Sincerity" },
    { number: 113, name: "Al-Falaq", englishName: "The Daybreak" },
    { number: 114, name: "An-Nas", englishName: "The Mankind" }
];

